server:
    port: 8080

spring:
    datasource:
        username: root
        password: 111111
        url: jdbc:mysql://192.168.10.100:3306/blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
        host: 192.168.10.100
        port: 6379
        database: 0
        password: 111111

    devtools:
        restart:
            enabled: true

mybatis:
    mapper-locations: classpath:mapper/*.xml

user:
    age: 300

